from tkinter import *
def change():
    lab["text"] = "tkinter_test"
win = Tk()
win.geometry("700x500")
win.option_add("*Font", "맑은고딕 20")
win.title("test")
lab = Label()
lab.config(text="test")
Btn = Button(win)
Btn.config(text="fool" , command=change)
vr = IntVar()
vb = Radiobutton(win, text="t" , value= 0, variable=True)
vb1 = Radiobutton(win, text="t1", value=1, variable=True)
sp =Spinbox(win)
sp.config(from_=-1, to =3)
ch = IntVar()
ch1 = IntVar()
ch2 = IntVar()
chk = Checkbutton(win)
sp.pack()
lab.pack()
Btn.pack()
vb.pack()
vb1.pack()
sp.pack()
chk.pack()
Button.pack
win.mainloop()
